### ISSUE TITLE
missing annotation files

### ISSUE THREAD

**Issue by Coke-Zhang** [dpcook/emt_dynamics#1]
missing file: how can get cell cycle annotation file on timecourse_processing.Rmd from processing_notbooks "~/Data/GeneLists/regev_lab_cell_cycle_genes.txt" 
"../data/LMOlist.csv"

**Comment by dpcook** [comment]
Sorry about that. Both files have been added to the repo. Let me know if there are any other hurdles

**Comment by Coke-Zhang** [comment]
> Sorry about that. Both files have been added to the repo. Let me know if there are any other hurdles

Thinks!
