### ISSUE TITLE
function MULTIseq.preProcess refers to a non-existing argument

### ISSUE THREAD

**Issue by romunov** [dpcook/emt_dynamics#3]
The call to [`MULTIseq.preProcess()` function](https://github.com/dpcook/emt_dynamics/blob/master/processing_notebooks/timecourse_processing.Rmd#L222) refers to argument `chemistry` but in the latest version of the `deMULTIplex` package, this argument doesn't exist. Tried to look at the history of the function on GitHub but couldn't find this argument. Can you elaborate on which version of the aforementioned package you're using or if you did any special tinkering of the function?

```r
readTable <- MULTIseq.preProcess(
  R1 = "../fastq/Mix1-Barcode/R1_paired.fastq.gz",
  R2 = "../fastq/Mix1-Barcode/R2_paired.fastq.gz",
  cellIDs = mix1_keep,
  chemistry = "V2"
)
```

This is a screenshot of the documentation from version 1.0.2.

![image](https://user-images.githubusercontent.com/544571/167406365-cf293fb1-7234-4c92-adad-928e3f829292.png)

**Comment by dpcook** [comment]
Hi @romunov--good catch. Sorry about yet another hurdle. They removed the `chemistry` parameter (which specified which version of the 10x 3' scRNA-seq was used) in favour of the more flexible setup of being able to manually specify the ranges in R1 that map to sample, cell, and UMI barcodes. 

Admittedly I would have to dig back to see which version of deMULTIplex this changed in, but you could just use the current version and specify `umi=c(17,26)` for the time course data (the "Mix1-4a/b" pools; done with the v2 kit, which just has a 2bp shorter UMI) and default parameters for the small molecule screen (the "Plate1-4" pools; done with the v3 kit).

**Comment by romunov** [comment]
I don't think of it as a hurtle, but rather like a late comer PR review. :) Thanks for the info, I'll specify parameters accordingly.

**Comment by dpcook** [comment]
Haha I appreciate it--future-proofing analysis code certainly wasn't on my mind as much as it should have been when I was working on this a couple years back :P. Let me know if you hit any more walls and I'll try to help sort it out!
