### ISSUE TITLE
Duplicated gene in "regev_lab_cell_cycle_genes.txt"

### ISSUE THREAD

**Issue by panchyni** [dpcook/emt_dynamics#4]
This is probably a minor issues, but I wanted to mention it just in case you are still using the same Cell Cycle scoring approach

The gene HJURP is duplicated in "regev_lab_cell_cycle_genes.txt" on lines 71 an 72, which leads to CENPA being omitted from the scoring process when g2m genes are defined from [44:97]

**Comment by dpcook** [comment]
I appreciate the heads up! I suspect the difference in the final cell cycle scores would be minor. Our of convenience, have been using Seurat's packaged cc.genes.updated.2019 for a while
