### ISSUE TITLE
Google drive link not working

### ISSUE THREAD

**Issue by elliewith** [dpcook/emt_dynamics#5]
Would it be possible to provide a link to the Seurat objects? Thanks!

**Comment by dpcook** [comment]
Apologies! Previous institute cut my google drive access. Have re-uploaded here: https://drive.google.com/drive/folders/1SIEIf7UswTv_0S6TypYsaRzMcfkfsgji?usp=share_link

Will update README accordingly. Let me know if there are any issues!
